apiVersion: v1
kind: Service
metadata:
  name: apica-react-app-service
spec:
  type: NodePort  
  selector:
    app: apica-react-app
  ports:
    - protocol: TCP
      port: 80         # Expose service on port 80
      targetPort: 3000  # Forward traffic to the container's port 3000
  
